import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
      className={`${inter.className} bg-gradient-to-r from-rose-100 to-teal-100`}>
        <div className="container mx-auto px-12 backdrop-blur bg-white/70 rounded mt-4 p-4">
          {children}
        </div>
      </body>
    </html>
  )
}
